// app/api/get-symbols/route.ts

// Complete list of F&O stocks (as of recent NSE list)
const FNO_SYMBOLS = [
  '360ONE', 'ABB', 'ABCAPITAL', 'ADANIENSOL', 'ADANIENT', 'ADANIGREEN', 'ADANIPORTS',
  'ALKEM', 'AMBER', 'AMBUJACEM', 'ANGELONE', 'APLAPOLLO', 'APOLLOHOSP', 'ASIANPAINT',
  'ASHOKLEY', 'ASTRAL', 'AUBANK', 'AUROPHARMA', 'AXISBANK', 'BAJAJ-AUTO', 'BAJAJFINSV',
  'BAJAJHLDNG', 'BAJFINANCE', 'BANDHANBNK', 'BANKBARODA', 'BANKINDIA', 'BDL', 'BEL',
  'BHARATFORG', 'BHARTIARTL', 'BHEL', 'BIOCON', 'BLUESTARCO', 'BOSCHLTD', 'BPCL',
  'BRITANNIA', 'BSE', 'CAMS', 'CANBK', 'CDSL', 'CGPOWER', 'CHOLAFIN', 'CIPLA', 'COALINDIA',
  'COFORGE', 'COLPAL', 'CONCOR', 'CROMPTON', 'CUMMINSIND', 'DABUR', 'DALBHARAT',
  'DELHIVERY', 'DIVISLAB', 'DIXON', 'DLF', 'DMART', 'DRREDDY', 'EICHERMOT', 'ETERNAL',
  'EXIDEIND', 'FEDERALBNK', 'FORTIS', 'GAIL', 'GLENMARK', 'GMRAIRPORT', 'GODREJCP',
  'GODREJPROP', 'GRASIM', 'HAL', 'HAVELLS', 'HCLTECH', 'HDFCAMC', 'HDFCBANK', 'HDFCLIFE',
  'HEROMOTOCO', 'HINDALCO', 'HINDZINC', 'HINDPETRO', 'HINDUNILVR', 'HUDCO', 'ICICIBANK',
  'ICICIGI', 'ICICIPRULI', 'IDEA', 'IDFCFIRSTB', 'IEX', 'IIFL', 'IGL', 'INDHOTEL',
  'INDIANB', 'INDIGO', 'INDUSINDBK', 'INDUSTOWER', 'INFY', 'INOXWIND', 'IOC', 'IREDA',
  'IRCTC','IRFC', 'ITC', 'JINDALSTEL', 'JIOFIN', 'JSWENERGY', 'JSWSTEEL', 'JUBLFOOD', 'KALYANKJIL',
  'KAYNES', 'KEI', 'KFINTECH', 'KPITTECH', 'KOTAKBANK', 'LAURUSLABS', 'LICHSGFIN', 'LICI',
  'LODHA', 'LT', 'LTF', 'LTIM', 'LUPIN', 'M&M', 'MANAPPURAM', 'MANKIND', 'MARICO', 'MARUTI',
  'MAXHEALTH', 'MAZDOCK', 'MCX', 'MFSL', 'MOTHERSON', 'MPHASIS', 'MUTHOOTFIN', 'NATIONALUM',
  'NAUKRI', 'NBCC', 'NESTLEIND', 'NHPC', 'NMDC', 'NTPC', 'NUVAMA', 'NYKAA', 'OBEROIRLTY',
  'OFSS', 'OIL', 'ONGC', 'PAGEIND', 'PATANJALI', 'PAYTM', 'PERSISTENT', 'PETRONET', 'PFC',
  'PGEL', 'PHOENIXLTD', 'PIDILITIND', 'PIIND', 'PNB', 'PNBHOUSING', 'POLICYBZR', 'POLYCAB',
  'POWERGRID', 'POWERINDIA', 'PPLPHARMA', 'PREMIERENE', 'PRESTIGE', 'RBLBANK', 'RECLTD',
  'RELIANCE', 'RVNL', 'SAIL', 'SAMMAANCAP', 'SBICARD', 'SBILIFE', 'SBIN', 'SHREECEM',
  'SHRIRAMFIN', 'SIEMENS', 'SOLARINDS', 'SONACOMS', 'SRF', 'SUPREMEIND', 'SUNPHARMA',
  'SUZLON', 'SWIGGY', 'SYNGENE', 'TATACONSUM', 'TATAELXSI', 'TATAPOWER', 'TATATECH',
  'TATASTEEL', 'TCS', 'TECHM', 'TIINDIA', 'TITAN', 'TMCV', 'TMPV', 'TORNTPHARM',
  'TORNTPOWER', 'TRENT', 'TVSMOTOR', 'ULTRACEMCO', 'UNIONBANK', 'UNITDSPR', 'UNOMINDA',
  'UPL', 'VBL', 'VEDL', 'VOLTAS', 'WAAREEENER', 'WIPRO', 'YESBANK', 'ZYDUSLIFE'
].sort();

export async function GET() {
  try {
    // Return the static list
    return Response.json(FNO_SYMBOLS, {
      headers: {
        'Cache-Control': 'public, max-age=86400' // Cache for 24 hours
      }
    });
  } catch (error) {
    console.error('Error:', error);
    // Still return the list even on error
    return Response.json(FNO_SYMBOLS);
  }
}

export const runtime = 'edge'; // Optional: Use edge runtime for faster response
export const dynamic = 'force-static'; // Mark as static